### ISSUE TITLE
Suggestion: Group and Lable your assemblies

### ISSUE THREAD

**Issue by sedorr** [andreisperid/E-TKT#30]
It would be cool if you could Group and Lable your assemblies to make navigating the STEP file easier, as currently it's kind of hard to find anything since stuff like the Electronic and mechanic assembiles aren't seperated and all parts are simply named brep.

![Screenshot 2023-04-18 213509](https://user-images.githubusercontent.com/34986602/232887657-921c933b-1352-4175-b111-62fc6d121b4b.png)

**Comment by andreisperid** [comment]
Can you please help with that @sedorr ? It would be of great value!

**Comment by sedorr** [comment]
I can try, but it would probably be much more helpful to do that in the native file + I don't really know what all the components and surfaces are.

**Comment by andreisperid** [comment]
I have exported that STEP from Rhino, which works mostly with polysurfaces, groups and layers.

![image](https://user-images.githubusercontent.com/15098003/232901568-6cd30445-bc45-45d5-b603-dd64a09611ae.png)

When I import it, it goes without problem and assembles polysurfaces, groups and layers. Do you have any clue if there are any import settings that might try to emulate that on Inventor? Maybe a preset for Rhino?

**Comment by sedorr** [comment]
![Screenshot 2023-04-18 225211](https://user-images.githubusercontent.com/34986602/232902390-5ea1f67e-2661-42f7-aec2-0482ece2de1d.png)

I tried it in Creo as well and it doesn't work.  I have a feeling that Rhino is diong the weird things since there are some parts (That I assume you imported) that are named.

![Screenshot 2023-04-18 225320](https://user-images.githubusercontent.com/34986602/232902874-897ef39f-6fc7-449e-96a8-0461bcd3b4b0.png)

Maybe try exporting your step files with a [different standard set](https://docs.mcneel.com/rhino/5/help/en-us/fileio/step_stp_import_export.htm), like AP214AutomotiveDesign.

**Comment by andreisperid** [comment]
That's exactly the standard that I have used. My bet is that the Rhino's taxonomy does not translate to other software.

What about other formats, such as IGES? Any idea of a standard that might work for you?

**Comment by sedorr** [comment]
Maybe just export all your printable parts as their own files? that would also be useful for some slicers, like PrusaSlicer, that take step directly.

**Comment by andreisperid** [comment]
Hi @sedorr, I've just uploaded separated STEP files in 2c0aaad
