### ISSUE TITLE
KiCad local library

### ISSUE THREAD

**Issue by andreisperid** [andreisperid/E-TKT#34]
I've used symbols, components and footprints installed on my local global library.

To facilitate collaboration and further iterations, I will try to bring this library locally to the project's KiCad directory.

**Comment by Knochi** [comment]
Since version 6, symbols are embedded into the KiCAD project, so you don‘t need to. 
It loaded perfectly fine on my site.

https://www.kicad.org/blog/2021/12/KiCad-6.0.0-Release/

> KiCad 6.0 also features a brand-new  schematic and symbol library file format, based on the format used for KiCad board and footprint files. This new format enables long-desired features such as embedding symbols used in a schematic directly in the schematic file, so that cache libraries are no longer needed

**Comment by andreisperid** [comment]
Nice, but what about the components, footprints and 3d models?

**Comment by Knochi** [comment]
For footprints it’s the same.
For 3D models you can use the plugin „Archive 3D Models“

**Comment by andreisperid** [comment]
So I think its alright, thanks @Knochi !
