### ISSUE TITLE
Text input should not offer autofill

### ISSUE THREAD

**Issue by andreisperid** [andreisperid/E-TKT#48]
This keyboard autocomplete bar has reappeared on Chrome (didn't test others).

<img src="https://user-images.githubusercontent.com/15098003/236252790-82f06cc4-23fa-4607-81e4-8ef5a246733d.png" width="30%">

I have [tried](https://stackoverflow.com/a/73466347/21637714) getting the  `type="search"`  back to the `<input>` and it worked while keeping the "send" functionality.

@sabeechen do you have anything strongly against that? Not ideal, but it works...

**Comment by sabeechen** [comment]
Sounds good to me, I hadn't realized autocomplete is what that was avoiding.

**Comment by andreisperid** [comment]
Alright, fixed on #50
